version: '3'
services:
  database:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vercel
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - virtual-network-2

  backend:
    build: backend/
    container_name: server_container
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - database
    networks:
      - virtual-network-1
      - virtual-network-2

  frontend:
    build: frontend/
    container_name: web_container
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - virtual-network-1

volumes:
  pgdata:

networks:
  virtual-network-1:
  virtual-network-2:
